// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_f2MlRWMgAiHuHrXFTb-6II4ff3w1os8',
    appId: '1:734395227402:web:b58d253ded1fea20532ef3',
    messagingSenderId: '734395227402',
    projectId: 'simplynotes-30c25',
    authDomain: 'simplynotes-30c25.firebaseapp.com',
    storageBucket: 'simplynotes-30c25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp5MSwc3upPhhIMBjOG5xq36EHhHDLvD4',
    appId: '1:734395227402:android:c9707dd2c9fa1087532ef3',
    messagingSenderId: '734395227402',
    projectId: 'simplynotes-30c25',
    storageBucket: 'simplynotes-30c25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgJPB7hCQdSbmU-G3vVq1umbP0laJ3TMs',
    appId: '1:734395227402:ios:b097e72e81e3cb22532ef3',
    messagingSenderId: '734395227402',
    projectId: 'simplynotes-30c25',
    storageBucket: 'simplynotes-30c25.appspot.com',
    iosClientId: '734395227402-af99t1qrkshm9jicq09gjkh9tuigm87n.apps.googleusercontent.com',
    iosBundleId: 'com.example.simplynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgJPB7hCQdSbmU-G3vVq1umbP0laJ3TMs',
    appId: '1:734395227402:ios:b097e72e81e3cb22532ef3',
    messagingSenderId: '734395227402',
    projectId: 'simplynotes-30c25',
    storageBucket: 'simplynotes-30c25.appspot.com',
    iosClientId: '734395227402-af99t1qrkshm9jicq09gjkh9tuigm87n.apps.googleusercontent.com',
    iosBundleId: 'com.example.simplynotes',
  );
}
